monitor=,preferred,auto,1

exec-once = noctalia

input {
    kb_layout = us
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

decoration {
    rounding = 8
}

bind = SUPER, RETURN, exec, kitty
bind = SUPER, D, exec, wofi --show drun

bind = SUPER, Q, killactive
bind = SUPER, M, exit

bind = SUPER, V, exec, pavucontrol